---

# 0. Look up OCP version in Cluster and set expected operator and channel
# -----------------------------------------------------------------------------
- name: "Look up cluster ocp version"
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    name: "version"
    kind: ClusterVersion
  register: ocp_version_lookup

- name: "Set ocp version number"
  when: ocp_version_lookup.resources[0] is defined
  set_fact:
    ocp_release: "{{ ocp_version_lookup.resources[0].status.desired.version }}"

- name: "Set storage operator and lso channel based on OCP release"
  set_fact:
    # As the default for the ocp_release is 4.12 then the default operator is odf (rather than ocs)
    storage_operator: "{{ (ocp_release is version('4.11.0', '>=')) | ternary('odf', 'ocs') }}"
    storage_operator_channel: "stable-{{ ocp_release | regex_search('^([0-9]+)\\.([0-9]+)') }}" # extract the ocp minor version

    # The lso operator channel subscription can be set to stable for all the versions
    local_storage_operator_channel: "stable"

# 1. Debug configuration
# -----------------------------------------------------------------------------
- name: "Debug ocs role configuration"
  debug:
    msg:
      - "OCP Release ............................ {{ ocp_release }}"
      - "LSO Operator channel ................... {{ local_storage_operator_channel }}"
      - "Storage Operator ....................... {{ storage_operator }}"
      - "Storage Operator channel ............... {{ storage_operator_channel }}"

# 2. Configure ODF or OCS backed by local-storage
# -----------------------------------------------------------------------------
- include_tasks: tasks/localstorage.yml
- include_tasks: tasks/storage.yml
