---


# 1. Create an image pull secret
# -----------------------------------------------------------------------------
- name: "Debug Entitlement Secret Creation"
  debug:
    msg:
      - "Target Namespace ....................... {{ project_namespace }}"
      - "Artifactory Username ................... {{ artifactory_username | default('<undefined>', true) }}"
      - "Artifactory Password ................... {{ artifactory_token | default('<undefined>', true) }}"
      - "ICR Username ........................... {{ icr_username | default('<undefined>', true) }}"
      - "ICR Password ........................... {{ icr_password | default('<undefined>', true) }}"

- name: "Create ibm-entitlement secret"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: ibm-entitlement
        namespace: '{{ project_namespace }}'
      data:
        .dockerconfigjson: "{{ lookup('template', 'templates/ibm-entitlement-with-artifactory.json.j2') | to_json | b64encode }}"

