---
# Add (MVI) Maximo Visual Inspection 8.8.x application to an existing MAS Core installation
#
# Dependencies:
#  - ansible-playbook ibm.mas_devops.oneclick_core

- hosts: localhost
  any_errors_fatal: true

  vars:
    # Application Installation
    # mas_app_id can be set to "health" to install manage in the "Health standalone" mode from this same playbook.
    mas_app_id: visualinspection
    mas_app_channel: "{{ lookup('env', 'MAS_APP_CHANNEL') | default('8.8.x', true) }}"

    # Application Configuration
    mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') | default('masdev', true) }}"

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'MAS_INSTANCE_ID') != ""
          - lookup('env', 'MAS_CONFIG_DIR') != ""
          - lookup('env', 'IBM_ENTITLEMENT_KEY') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_devops.nvidia_gpu
    - ibm.mas_devops.suite_app_install
    - ibm.mas_devops.suite_app_config
