---
- hosts: localhost
  any_errors_fatal: true
  pre_tasks:
    - name: Check for required environment variables
      assert:
        that: lookup('env', 'MAS_CATALOG_VERSION') != ""
        fail_msg: "You must provide the catalog version to update to (e.g. 'v8-230314-amd64', 'v8-230414-amd64')"

  roles:
    - ibm.mas_devops.ibm_catalogs
