---
# 1. Update API Server
# -----------------------------------------------------------------------------

# https://github.ibm.com/wiotp/tracker/issues/11556

- name: "Backwards compatability for 'quickburn' cluster type"
  when: cluster_type == "quickburn"
  set_fact:
    cluster_type: "fyre"

# 2. Debug Info
# -----------------------------------------------------------------------------
- name: "fyre : Debug information"
  debug:
    msg:
      - "Cluster type ................. {{ cluster_type }}"
      - "ocp_fips_enabled ............. {{ ocp_fips_enabled }}"

# Update API Server to custom tlsprofile to include semeru compatible ciphers
- include_tasks: tasks/update-apiserver.yml
  when:
    - cluster_type in ['fyre', 'ipi']
    - ocp_fips_enabled
