---
# Nvidia gpu namespace
gpu_namespace: "{{ lookup('env', 'GPU_NAMESPACE') | default('nvidia-gpu-operator', true) }}"

# Set channel for install and updates
gpu_channel: "{{ lookup('env', 'GPU_CHANNEL') | default('v22.9', true) }}"

# GPU driver settings
_gpu_driver_version: "{{ lookup('env', 'GPU_DRIVER_VERSION') }}"
rhel8_driver_version: 470.182.03 # default for Rhel 8 and corresponding rhcos
rhel7_driver_version: 450.80.02  # default for Rhel 7 and corresponding rhcos
gpu_driver_repository_path: "{{ lookup('env', 'GPU_DRIVER_REPOSITORY_PATH') | default('nvcr.io/nvidia', true) }}"


# Variables for Node Feature Discovery Operator
# NFD namespace
nfd_namespace: "{{ lookup('env', 'NFD_NAMESPACE') | default('openshift-nfd', true) }}"

# channel for nfd install and updates
nfd_channel: "{{ lookup('env', 'NFD_CHANNEL') | default('stable', true) }}"
