---

# Choose which catalog source to use for the MAS install, default to the IBM operator catalog
mas_app_catalog_source: "{{ lookup('env', 'MAS_APP_CATALOG_SOURCE') | default('ibm-operator-catalog', true) }}"
mas_app_upgrade_strategy: "{{ lookup('env', 'MAS_APP_UPGRADE_STRATEGY') | default('Automatic', true) }}"

# Which MAS channel to subscribe to
mas_app_channel: "{{ lookup('env', 'MAS_APP_CHANNEL') | default('8.x', true) }}"

# MAS configuration
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"

# MAS configuration - Entitlement
mas_entitlement_username: "{{ lookup('env', 'MAS_ENTITLEMENT_USERNAME') | default('cp', true) }}"
ibm_entitlement_key: "{{ lookup('env', 'IBM_ENTITLEMENT_KEY') }}"
mas_entitlement_key: "{{ lookup('env', 'MAS_ENTITLEMENT_KEY') | default(ibm_entitlement_key, true) }}"

# MAS application configuration
mas_app_id: "{{ lookup('env', 'MAS_APP_ID') }}"
mas_app_plan: "{{ lookup('env', 'MAS_APP_PLAN') }}"

# Bindings
mas_app_bindings_jdbc: "{{ lookup('env', 'MAS_APP_BINDINGS_JDBC') | default('system', true) }}"

# Additional Visual Inspection Settings
mas_app_settings_visualinspection_storage_class: "{{ lookup('env', 'MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_CLASS') }}"
mas_app_settings_visualinspection_storage_size: "{{ lookup('env', 'MAS_APP_SETTINGS_VISUALINSPECTION_STORAGE_SIZE') | default('100Gi', true) }}"

# Additional IoT Settings
mas_app_settings_iot_deployment_size: "{{ lookup('env', 'MAS_APP_SETTINGS_IOT_DEPLOYMENT_SIZE') | default('small', true) }}"
mas_app_settings_iot_fpl_pvc_storage_class: "{{ lookup('env', 'MAS_APP_SETTINGS_IOT_FPL_PVC_STORAGE_CLASS') }}"
mas_app_settings_iot_fpl_router_pvc_size: "{{ lookup('env', 'MAS_APP_SETTINGS_IOT_FPL_ROUTER_PVC_SIZE') | default('100Gi', true) }}"
mas_app_settings_iot_fpl_executor_pvc_size: "{{ lookup('env', 'MAS_APP_SETTINGS_IOT_FPL_EXECUTOR_PVC_SIZE') | default('100Gi', true) }}"
mas_app_settings_iot_mqttbroker_pvc_storage_class: "{{ lookup('env', 'MAS_APP_SETTINGS_IOT_MQTTBROKER_PVC_STORAGE_CLASS') }}"
mas_app_settings_iot_mqttbroker_pvc_size: "{{ lookup('env', 'MAS_APP_SETTINGS_IOT_MQTTBROKER_PVC_SIZE') | default('100Gi', true) }}"

# Additional Monitor Settings
mas_app_settings_monitor_deployment_size: "{{ lookup('env', 'MAS_APP_SETTINGS_MONITOR_DEPLOYMENT_SIZE') | default('dev', true) }}"

# Custom Labels
custom_labels: "{{ lookup('env', 'CUSTOM_LABELS') | default(None, true) | string | ibm.mas_devops.string2dict() }}"
